final Map<String, String> mediaTypeMap = {
  'pdf': 'application/pdf',
  'jpg': 'image/jpeg',
  'jpeg': 'image/jpeg',
  'jfif': 'image/jpeg',
  'jpe': 'image/jpeg',
  'jif': 'image/jpeg',
  'png': 'image/png',
  'gif': 'image/gif',
  'webp': 'image/webp',
  'doc': 'application/msword',
  'docx': 'application/msword',
  'xls': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'zip': 'application/zip',
  'xml': 'application/xml',
  'pfx': 'application/x-pkcs12',
  'p12': 'application/x-pkcs12',
  'crt': 'application/x-x509-ca-cert',
  'cer': 'application/x-x509-ca-cert',
  'der': 'application/x-x509-ca-cert',
  'pem': 'application/x-pem-file',
};
