name: aastera
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

executables:
  aastera: aastera_cli

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.0
  io: ^1.0.4 
  path: ^1.9.0
  process_run: ^0.13.0 

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
